// Code generated by mockery v2.15.0. DO NOT EDIT.

package repositories

import (
	context "context"

	models "github.com/nronas/invasion_sim/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockCitiesRepository is an autogenerated mock type for the CitiesRepository type
type MockCitiesRepository struct {
	mock.Mock
}

type MockCitiesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCitiesRepository) EXPECT() *MockCitiesRepository_Expecter {
	return &MockCitiesRepository_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockCitiesRepository) GetAll(ctx context.Context) ([]*models.City, error) {
	ret := _m.Called(ctx)

	var r0 []*models.City
	if rf, ok := ret.Get(0).(func(context.Context) []*models.City); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.City)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCitiesRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockCitiesRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCitiesRepository_Expecter) GetAll(ctx interface{}) *MockCitiesRepository_GetAll_Call {
	return &MockCitiesRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockCitiesRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockCitiesRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCitiesRepository_GetAll_Call) Return(_a0 []*models.City, _a1 error) *MockCitiesRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewMockCitiesRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockCitiesRepository creates a new instance of MockCitiesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockCitiesRepository(t mockConstructorTestingTNewMockCitiesRepository) *MockCitiesRepository {
	mock := &MockCitiesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
